### ISSUE TITLE
Add becnhmark for biome linter (formerly known as rome.tools)

### ISSUE THREAD

**Issue by cliffordfajardo** [oxc-project/bench-javascript-linter#1]
Hi oxc team,

On your homepage I saw that there is a comparison with oxc and eslint for linting
![image](https://github.com/oxc-project/bench-javascript-linter/assets/6743796/c8eba906-fae3-4bbe-83c6-e5d1d1924966)

Would you be open to the idea of adding benchmark testing [biome](https://biomejs.dev/) (formerly known as rome)?
Biome is another rust based tool that is gainning popularity in the web ecosystem; as someone looking to adopt a modern linter that scales (_I work at a company with huge codebases & user base is 1billion+ users for context_)

**Comment by Boshen** [comment]
Please note the first line of the README:

> This benchmark only compares with ESLint and does not compare against Rome because the rules do not match.

I'll correct it with Biome.
