### ISSUE TITLE
Eslint v9

### ISSUE THREAD

**Issue by XanderD99** [oxc-project/bench-javascript-linter#9]
I noticed you tried to update to eslint v9 but it broke everything: 

you need to update the config file, since the format has changed from v8 to v9. Easiest way is to simply run: `npx @eslint/migrate-config .eslintrc.json`. 

More info [here](https://eslint.org/docs/latest/use/configure/migration-guide)

Here are my results after running the benchmarks (2021 MacBook M1 Pro, 32GB Ram, 10 Cores (8 performance and 2 efficiency)).

### eslint v8 x oxc

```bash
Benchmark 1: oxc ./node_modules/.bin/oxlint ./tmp/vscode/src
  Time (mean ± σ):     584.6 ms ±  11.5 ms    [User: 3640.2 ms, System: 196.4 ms]
  Range (min … max):   573.8 ms … 612.2 ms    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Benchmark 2: eslint ./node_modules/.bin/eslint -c .eslintrc.json ./tmp/vscode/src
  Time (mean ± σ):     33.316 s ±  0.478 s    [User: 50.109 s, System: 2.097 s]
  Range (min … max):   32.560 s … 34.375 s    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Summary
  oxc ran
   56.99 ± 1.39 times faster than eslint
```

### eslint v9 x oxc

```bash
Benchmark 1: oxc ./node_modules/.bin/oxlint ./tmp/vscode/src
  Time (mean ± σ):     611.7 ms ±  24.7 ms    [User: 3649.9 ms, System: 205.6 ms]
  Range (min … max):   575.0 ms … 647.0 ms    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Benchmark 2: eslint ./node_modules/.bin/eslint -c eslint.config.mjs ./tmp/vscode/src
  Time (mean ± σ):     35.190 s ±  1.114 s    [User: 53.655 s, System: 2.598 s]
  Range (min … max):   33.256 s … 36.921 s    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Summary
  oxc ran
   57.53 ± 2.95 times faster than eslint
```

Weirdly enough v9 seems to be slower? But I do think this may be due to the config file not being optimised for v9. Anyway I don't have enough knowledge about eslint to actually confirm this.

**Comment by Boshen** [comment]
Thank you for the info! I dread wasting time upgrading to v9 😅
